/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class richard_ztesoft_com_ndkfirstproject_ndk_NDKTestLib */

#ifndef _Included_richard_ztesoft_com_ndkfirstproject_ndk_NDKTestLib
#define _Included_richard_ztesoft_com_ndkfirstproject_ndk_NDKTestLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     richard_ztesoft_com_ndkfirstproject_ndk_NDKTestLib
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_richard_ztesoft_com_ndkfirstproject_ndk_NDKTestLib_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
